CREATE TABLE [dbo].[Users]
(
  [id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  [google_id] NVARCHAR(255) NOT NULL UNIQUE,
  [email] NVARCHAR(255) NOT NULL UNIQUE,
  [name] NVARCHAR(255) NOT NULL,
  [picture] NVARCHAR(MAX) NULL,
  [created_at] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  [updated_at] DATETIME2 NULL
)
